services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ambiente_php_estagiarios
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped